name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run unit tests
      run: ./gradlew test

  integration-test:
    needs: build-and-test
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:17.3-alpine
        env:
          POSTGRES_DB: coworking_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Ernesto
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Wait for PostgreSQL
      run: sleep 15

    - name: Run integration tests
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/coworking_db
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: Ernesto
      run: ./gradlew integrationTest

  docker-build:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker images
      run: docker compose build

    - name: Push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/coworking-app:latest
          ${{ secrets.DOCKER_USERNAME }}/coworking-app:${{ github.sha }}
